Repository Life-Science-Project/LifeScience, pull requests merged in 2021-05, with the labels that each got.

#139 article secure antMatcher fix
  backend/src/main/kotlin/com/jetbrains/life_science/config/WebSecurityConfig.kt
Labels: bug

#143 id added to section view
  backend/src/main/kotlin/com/jetbrains/life_science/article/section/view/SectionView.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/section/view/SectionViewMapper.kt
Labels: fix

#153 Fix issue with refresh token being updated on login
  backend/src/main/kotlin/com/jetbrains/life_science/auth/AuthController.kt
  backend/src/main/kotlin/com/jetbrains/life_science/auth/AuthTokens.kt
Labels: fix

#157 Atomary article creation via cascade
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/dto/ContentInnerDTO.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/dto/ContentInnerDTOToInfoAdapter.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/factory/ContentFactory.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/service/ContentInfo.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/section/dto/SectionInnerDTO.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/section/dto/SectionInnerDTOToInfoAdapter.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/version/controller/ArticleVersionController.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/version/dto/ArticleVersionCreationDTO.kt
  backend/src/test/kotlin/com/jetbrains/life_science/article/version/controller/ArticleVersionControllerTest.kt
Labels: enhancement

#188 article version full page fixed
  backend/src/main/kotlin/com/jetbrains/life_science/article/version/view/ArticleVersionViewMapper.kt
Labels: bug

#194 full page access fixes
  backend/src/main/kotlin/com/jetbrains/life_science/article/version/controller/ArticleVersionController.kt
Labels: bug, fix

#196 complete version access bug fix
  backend/src/main/kotlin/com/jetbrains/life_science/config/WebSecurityConfig.kt
Labels: bug, fix

#197 security fix
  backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
Labels: bug, fix

#202 Add category
  frontend/src/App.js
  frontend/src/api/category-api.js
  frontend/src/components/NewArticle/new-article-container.js
  frontend/src/components/NewProtocol/new-protocol-container.js
  frontend/src/components/main/Categories/EditCategory/Parts/categoryForm.js
  frontend/src/components/main/Categories/EditCategory/Parts/editCategory.js
  frontend/src/components/main/Categories/EditCategory/Parts/newCategory.js
  frontend/src/components/main/Categories/EditCategory/editCategory.css
  frontend/src/components/main/Categories/EditCategory/editCategoryContainer.js
  frontend/src/components/main/Categories/EditCategory/shortCategory.js
  frontend/src/components/main/Categories/categories.js
  frontend/src/components/main/Categories/categoriesContainer.js
  frontend/src/redux/actions/category-actions.js
  frontend/src/redux/category-reducer.js
  frontend/src/redux/init-reducer.js
Labels: enhancement

#205 Api fix
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/controller/ContentController.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/section/view/SectionViewMapper.kt
Labels: bug, fix

#208 copy method fix
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/service/ContentServiceImpl.kt
Labels: bug, fix

#212 Edit category patches
  frontend/src/components/common/Button/sendByUrlButton.js
  frontend/src/components/main/Categories/EditCategory/Parts/categoryForm.js
  frontend/src/components/main/Categories/EditCategory/Parts/editCategory.js
  frontend/src/components/main/Categories/EditCategory/Parts/newCategory.js
  frontend/src/components/main/Categories/EditCategory/editCategoryContainer.js
  frontend/src/components/main/Categories/EditCategory/shortCategory.js
  frontend/src/components/main/Categories/categoriesContainer.js
  frontend/src/redux/actions/category-actions.js
  frontend/src/redux/category-reducer.js
Labels: bug, fix

#213 New edit user form
  frontend/src/components/Navbar/navbar.js
  frontend/src/components/main/ProfilePage/Parts/Favourites/favourites.js
  frontend/src/components/main/ProfilePage/Parts/Favourites/shortMethodPreview.js
  frontend/src/components/main/ProfilePage/Parts/User/EditUserData/editUserData.css
  frontend/src/components/main/ProfilePage/Parts/User/EditUserData/editUserData.js
  frontend/src/components/main/ProfilePage/Parts/User/UserParts/userAvatar.js
  frontend/src/components/main/ProfilePage/Parts/User/UserParts/userOrganisations.js
  frontend/src/components/main/ProfilePage/Parts/User/userPerfomance.js
  frontend/src/components/main/ProfilePage/profilePageContainer.js
  frontend/src/redux/method-reducer.js
  frontend/src/redux/new-protocol-reducer.js
  frontend/src/redux/users-reducer.js
  frontend/src/utils/common.js
  frontend/src/utils/user.js
Labels: bug, fix

#214 Content tests
  backend/build.gradle.kts
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/controller/ContentController.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/dto/ContentDTO.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/dto/ContentDTOToInfoAdapter.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/service/ContentService.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/service/ContentServiceImpl.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/view/ContentView.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/version/service/ContentVersionServiceImpl.kt
  backend/src/main/kotlin/com/jetbrains/life_science/exception/advice/ControllerAdvisor.kt
  backend/src/test/kotlin/com/jetbrains/life_science/ControllerTest.kt
  backend/src/test/kotlin/com/jetbrains/life_science/article/content/publish/controller/ContentControllerTest.kt
  backend/src/test/kotlin/com/jetbrains/life_science/article/review/response/controller/ReviewControllerTest.kt
  backend/src/test/kotlin/com/jetbrains/life_science/article/version/controller/ArticleVersionControllerTest.kt
  backend/src/test/kotlin/com/jetbrains/life_science/util/populator/ElasticPopulator.kt
  backend/src/test/kotlin/com/jetbrains/life_science/util/populator/Populator.kt
  backend/src/test/resources/elastic/content.json
  backend/src/test/resources/elastic/content_version.json
  backend/src/test/resources/scripts/add_test_data.sql
Labels: fix, test
