Repository Life-Science-Project/LifeScience, pull requests merged in 2021-04, with the labels that each got.

#88 Content version separate index
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/controller/ContentController.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/index/IndexCoordinatesProvider.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/controller/ContentController.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/dto/ContentDTO.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/dto/ContentDTOToInfoAdapter.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/entity/Content.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/factory/ContentFactory.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/repository/ContentRepository.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/repository/ContentRepositoryCustom.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/repository/ContentRepositoryImpl.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/service/ContentInfo.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/service/ContentService.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/service/ContentServiceImpl.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/view/ContentView.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/publish/view/ContentViewMapper.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/version/repository/ContentVersionRepository.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/version/repository/ContentVersionRepositoryImpl.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/version/service/ContentVersionService.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/content/version/service/ContentVersionServiceImpl.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/section/service/SectionService.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/section/service/SectionServiceImpl.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/section/view/SectionView.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/section/view/SectionViewMapper.kt
  backend/src/main/kotlin/com/jetbrains/life_science/article/version/service/ArticleVersionServiceImpl.kt
  backend/src/main/kotlin/com/jetbrains/life_science/exception/ContentIsNotEditableException.kt
  backend/src/main/kotlin/com/jetbrains/life_science/exception/IllegalAccessException.kt
  backend/src/main/kotlin/com/jetbrains/life_science/exception/advice/ControllerAdvisor.kt
  backend/src/main/kotlin/com/jetbrains/life_science/util/elastic/CustomIndexElasticsearchRepository.kt
  backend/src/test/kotlin/com/jetbrains/life_science/LifeScienceApplicationTests.kt
  backend/src/test/kotlin/com/jetbrains/life_science/category/service/CategoryServiceImplTest.kt
Labels: enhancement

#101 Now f5 works fine
  backend/src/main/kotlin/com/jetbrains/life_science/config/WebConfig.kt
Labels: bug

#102 login api fixed
  backend/src/main/kotlin/com/jetbrains/life_science/config/jwt/JWTResponse.kt
  backend/src/main/kotlin/com/jetbrains/life_science/user/credentials/controller/AuthController.kt
  backend/src/main/kotlin/com/jetbrains/life_science/user/credentials/view/LoginJWTView.kt
  backend/src/main/kotlin/com/jetbrains/life_science/user/credentials/view/LoginJWTViewMapper.kt
  backend/src/main/kotlin/com/jetbrains/life_science/user/details/view/UserShortView.kt
  backend/src/main/kotlin/com/jetbrains/life_science/user/details/view/UserViewMapper.kt
Labels: fix
